---
title             : "Within-person replicability of idiographic networks"
shorttitle        : ""

author: 
  - name          : "Ricarda K. K. Proppert"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : ""
    email         : "ricarda.proppert@gmail.com"

  
  - name          : "Eiko I. Fried"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Clinical Psychology, Leiden University, The Netherlands"


abstract: |
  Evidence-based mental health programs have long conceptualized mental disorders in terms of interactions between thoughts, feelings, behaviours and external factors.
  
  Idiographic network models are a relatively novel way of modeling such longitudinal intra-individual symptom interactions. However, these methods are not without limitations, and concerns have been raised about the replicability and stability of estimated networks.
  
  While methods to assess network replicability have been developed for cross-sectional data, no such method exists for single-subject data. The extend to which idiographic networks are stable, or vary over time, is unknown.
  
  In the current work, we reanalyse daily symptom records of people with personality disorders to explore the replicability of idiographic networks over time, as well as the degree to which network replicability varies across individuals. We further explore factors which may relate to inter-individual variation in replicability using predictive LASSO regression.

  
keywords          : ""
wordcount         : ""


floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf

bibliography: references.bib
---

```{r setup, include = FALSE}
library("papaja")
# r_refs("r-references.bib")

# sessionInfo()


```

<!--
TODO: 

- place authornote in YAML again, currently throws error due to papaja bug. 
Issue: https://github.com/crsh/papaja/issues/225

authornote: "Research Master Clinical- and Health psychology (combined track) Master thesis. We thank Dr. Aidan Wright, Pittsburg University, and his colleagues for sharing their data with us. The data and reproducible analysis script are available upon request."

- Abstract needs Results and Implication

- Specify authorship roles in YAML (see Master guidelines)

-->

# Introduction

## Idiographic networks

Idiographic network models are of growing interest to clinical psychology because they may address two recently voiced calls in clinical psychology:

Firstly, there seems to be a need for psychological research to re-orient towards idiographic methods that study intra-individual processes as opposed to group-level differences [@Molenaar2004].

Secondly, scholars are proposing a paradigm shift from reductionism towards studying the complexity of psychological phenomena. The Network theory of mental disorders [@BorsboomCramer2013; @CramerEtAl2010] attempts to integrate psychology with insights and methods from complexity science, proposing a novel but well-received theoretical framework to study and understand the underpinnings of psychopathology.

It conceptualizes psychopathology as an emergent state of dynamically interacting psychological symptoms, as well as factors external to this system. This account seems closely aligned with established clinical practices where informal case conceptualizations in form of path diagrams are used to describe the proposed mechanisms of a given disorder as a dysfunctional cycle of mutually interacting stressors, thoughts, feelings and behaviors.

With the ongoing development of statistical methods to visualize and quantify such system's structures and behaviors, called psychological networks or psychonetrics (REF), an increasing body of research is now applying this framework to study symptom networks in people with mental disorders.

Psychological networks consist of elements (nodes) and their interactions (edges), forming a complex system. Nodes represent psychological or other variables, such as symptoms, stressors, or behaviors. Edges represent relationships between these variables. These relationships may be directed or undirected and are thought result from of a multitude of mechanisms giving rise to their association, which may not necessarily be known or defined.

Most of the psychological network research so far is based on group-level analyses and cross-sectional comparisons, mainly for practical reasons such as availability of existing data-sets and power constraints. There is, however, a growing interest in personalized network models of intra-individual symptom dynamics, and their potential to inform and monitor mental health care (eg., @FrumkinEtAl2020; @HoweEtAl2020; @CavigliaColeman2016; @HoffartJohnson2020).

Explain estimation procedures and assumptions in more detail:

-   explain graphicalVAR estimation
-   stationarity
-   multivariate normality
-   no measurement error
-   mention related methods that we do not use here, and why (mlVAR, baysian, all the other not so networky idioraphic models (see idio review)

## Current challenges in research on idiographic networks

-   require high power, which is difficult to obtain in longitudinal N=1 study (burdensome)

-   even if power is high and networks can be estimated reliably, longitudinal stability of networks is unknown (ie how they generalize to different time within same individual)

-   stability of estimates is an important issue (beyond scopoe here but explain this as important limitation)

-   even if estimates stable, replicability not warranted:

 -   How stable is the data generating process we try to capture? Is this the process of interest? Is it malleable? Phase transitions?

-   feasibility

### Implications of high stability

-   would mean that this line of research is feasible
-   can we get methodological recommendations out of this, eg. on design of studies, planned missingness, feasibility of daily as opposed to more frequent prompts and harnessing benefits of that

### Implications of low stability

-   underpowered? (in)stability of estimates?
-   warrants caution regarding the inferences we draw (momentary impression of item correlations in certain period of time vs. stable process which extends beyond this period and could inform interventions (TODO: related to predictive value of networks?)
-   measurement error assumption: are we just capturing noise? (unlikely but still an issue to think about)
-    is extending measurement period instead of increasing frequency a good solution, eg. with planned missingness, or is non-stationarity and low replicability too much of concern?

## Research Questions

-   Goal of this work: initial impression of intra-individual replicability of idiographic networks

RQ1: How stable are estimated idiogr network structures over time?

RQ2: What factors may predict inter-individual variation in intra-individual replicability?

-   speculate about some people's experiences changing more over the course of weeks than others, eg. due to underlying conditions, comorbidity, being in treatment or not, times of extreme stress

-   look for any initial evidence for or against this possibility

# Methods

A recent simulation study (preprint Mansueto), ... required power would be bla.

The current work aims to add to this line of research by testing the stability of personalized networks under clinically realistic constraints. To this end, we re-analyze 100-days long daily diary data collected in a clinical sample with personality disorders (cite Aidan), which was kindly made available by the original authors. We assume this data set to be representative of a clinically realistic sampling scheme for two reasons: Firstly, measuring symptoms daily as opposed to more often (eg. 4 times daily, as often used in ESM), is an already established method to enhance clinical diagnosis of certain disorders (find info), and even used as therapeutic technique in evidence-based clinical treatments (tracking mood to better understand ones emotional life, find source?). Secondly, daily measurements with a timescale of 1 day in between measuements may be desirable for modeling variables that typically fluctuate on a daily level only and are more within the control of the patient, such as sleep or exercise. Furthermore, the time frame of 100 days may strike a balance of being at the lower end of what may be needed for sufficient statistical power, and at the higher end of what may be an acceptable burden to pose on clinically distressed patients, as well as realistic for typical treatment durations.

## Data Set

<!-- 
- Describe Study design by Aidan
- List included variables: Base line and EMA
- Describe why data is suited for this method
-->

A summarized version of the data are published HERE, an overview of all available variables can be found in Appendix A.

The original study design by which the data were collected are described in detail in previous publications [@WrightEtAl2015; @WrightSimms; @WrightEtAl2015a]. The study investigated daily dynamics in affect, stress, andexpressions of personality disorder, along with some lifestyle variables such as self-reported sleep, drug and alcohol use, and overall functioning. Participants were recruited from an ongoing clinical study (N=628, REFS SIMMS Goldberg Welte 2014; simms et al 2011) that targeted individuals who had received psychiatric treatment within the previous two years, recruited via flyers distributed at mental health clinics across Western New York, USA. They were invited for study participation if they met the diagnostic requirements of any personality disorder during the initial structured clinical interview conducted for the parent study (SCID-II, TODO REF), and if they had daily internet access via a computer or mobile device. 116 participants were initially enrolled, of which 101 participants completed at least 30 of the desired 100 daily measurements.

In selecting this data set for the present study, we balanced three main considerations: Availability: A shorter version of this data are openly available, and the original author expressed their willingness to share the full data in response to a broad request on twitter (TODO: link the post).

We chose this data set for this study for three main reasons: It was one of the few available clinical longitudinal data sets we could find, a summary data set had already been published, and we believe the design to be a good representation of a feasible clinical setting: Daily records are an already well-established method for enhancong diagnosis and monitoring patients daily lives, and asks less burden of participants compared to more intensive EMA methods. Secondly, the duration of 100-days consistent data collection was long enough so that splitting the data seemed feasible. Recorded variables - although being collected in a sample of people diagnosed with a personality disorder - were general enough to not be restricted to a certain mental disorder.

Representativeness of realistic clinical designs: Applications of idiographic network models are currently scarce, mainly because they require well-powered data that necessarily come at increased burden to the participants. To improve power in single-subject longitudinal designs, such as ESM / EMA or daily diary studies, Participants are required to either provide more intensive momentary data, or provide less intensive (eg., daily) records over a longer period. Specific power requirements for idiographic networks are still unknown. Some simulation work suggests that ..... , depending on the number of estimated nodes and amount of missingness. Given that daily diaries a more established method of data collection in clinical research and mental health care, and assuming that it poses less burden on participants compared to more intensive sampling frames, we hope that this data is at the higher end of what seems realistic and feasible for future study designs and applications. Simultaneously, although no precise power estimates are currently available, we hope that meets the minimum power needed for our analyses (up to 50 data points per individual, per network).

- methodological assumptions (study duration, sample size, stationarity of variables.

-  Participants completed daily measurements over the course of 100 consecutive days. Participants completed surveys at roughly the same time each night, depending on their individual schedule. Therefore, therefore, this data set is expected to meet the assumption of roughly equal time intervals in between measurements (REF mlVAR).

Participants started measurements asynchronically, so that no sample-wide history effects should affect our results on longitudinal within-person stability of esitmated networks.

Furthermore, the original authors reported stability of means and variances of expressions of daily psychopathology in (REF), so that we expect most variables to meet the assumption of stationarity (REF).


## Analysis plan

### Pre-processing:

To prepare the network estimation process, data will be explored and if necessary transformed according to the following steps.

1)  Inspect missing data:

-   exclude participants with fewer than 30 responses as done in REF original publications

-   Split data into first 50days (T1) and last 50 days (T2)

-   Compute levels of missingness per subject per item per T

-   Per subject, per variable, per T, compute:

    -   Mean

    -   Variance

    -   Skew

    -   number of missing responses

-   Per subject, exclude items with less than 25 responses in either T1 or T2\
    As we aim to compare the network structures of T1 and T2, participants should have provided sufficient data in both time periods. Even though imputation using the Kalman filter has been shown to recover true network structures well under mcar assumption, but Mansueto suggests that performance declined dramatically at 50% levels of missingness (REF) in network with 75 time points.

-   Impute remaining missing data using Kalman filter (REF Harvey,A.C.(1990). Forecasting, structural time series models and the Kalman filter.Cambridge,UK:Cambridgeuniversity press., REF Code Mansueto)

-   Compute composite variables:

    -   StressSUM = Sum(Stress1:Stress7)

    -   Positive Affect = Mean((Active, Alter, Attentive, Determined, Inspired)

    -   Negative Affect = Mean(

-   Per subject, retrieve 20 items with highest variance (T1 and T2)

-   Per subject, select 6 variables subjectively optimizing the following aspects:

    -   few missing (imputed) responses

    -   high variance which seems realistic and not due to measurement error

    -   little skew, so no transformation may be needed

    -   mean and variance roughly equal at T1 and T2 (so no obvious signs of non-stationarity

    -   defendable theoretical relationship (lagged or contemporaneous) with other selected items

-   Inspect non-stationarity of selected items and detrend linear effects of time (on T1 and T2 together so this does not affect comparisons)

-   Inspect skew of selected items and transform to normality if this seems necessary

<!--
    - Explore Means, variances and missingness per individual per variable
    - per subject, select 6 variables to be included in person specific network, subjectively optimizing the following aspects:
      - sufficient variance per variable
      - little skew
      - fewer missing responses
      - meaningful combination of items, ie pick variables for which we can imagine a plausible relationshipt at daily interval
    - Impute missing data using Kalman filter
    - Insxpect stationarity of means and variances. Detrend data if deviations seem severe.
    - Motivation to choose variables per subject: Heterogeneous sample, includes people with varios types of personality disorder and comorbidity. Too few data points to estimate larger network
    -->

### Network estimation

-   estimate symptom networks per subject, per time frame:

-   gVar() package

-   regularized networks: sparse, err on side of Type 1 errors in attempt to not overfit and increase replicability

-   how deal with empty networks and their cor???\
    What to do with too many empty networks?

-   tuning parameter allowing for more false positives (so probably cor lower then) --\>

### Estimate network replicability:

<!--
    - calculate network replicability as the correlation between T1 and T2 adjacency matrices (matrices of estimated pathcoefficients of every pair of variables included in the network)
    - Note: other measures have been proposed. 
    - Motivation to use cor():
      - using the correlation is a convenient way for us to derive a simple metric with clear interpretation. For example, it is immune to a linear increase / decrease that affects path coefficients equally, as this would not change the interpretation of the global network structure. 
      - It also treats T1 and T2 networks equally (as opposed to confirmatory modelling techniques / simulation techniques in which one structure act as a "to be assumed true" reference network).
      - it is independent of power, assuming T1 and T2 are equally powered (which is the case here)
    - Alternative ways to compare networks exist: Network comparison test, specificity and sensitivity of network recovery, the Forbes thing which has been criticised, confirmatory network modelling (see psychonetrics?)- composite score?
    -->

### Exploratory analysis of contributing factors:

-   level of initial missingness (because this influences performance of Kalman Filter)

-   being in treatment

-   number of comorbid diagnoses

-   type of PD?

Models will be estimated using the open-source package graphicalVAR [@zotero-7045](TODO Epskamp, 2017) in which networks are regularized using penalized maximum likelihood estimation [@AbegazWit2013].

Other methods to estimate idiographic network models exist, which eacht their own benefits. ... In contrast to multilevel network estimation, which may be preferred for it's ability to estimate indivududal networks while borrowing infomation from the group-level and requires less data points [@EpskampEtAl2018b]. However, in multilevel modeling, individual networks are restricted to have the same structure across individuals, which is an unlikely assumption in our heterogeneous sample.

Why predictive LASSO regression:

-   problem of predictor selection better approached by LASSO than by step-wise regression :)

-   clearer interpretation of the models practical value: out-of sample validation in holdout sample to give realistic impression of model performance vs overfitting

Things to control for:


-   nr of missing / imputed data points per individual

-   if we have to vary this across people: nr of included nodes, tuning parameter

-   other characteristics of included variables? (variance, non-stationarity,

### Potential issues and solutions:

<!--
- A large proportion of estimated networks may be empty due to low power. (Recent simulation work suggests that 75 time points or more are neccessary for reliable restimation for idiographic network of 6 variables with no missing data, but power is still a complicated issue as it depends on many features of the data and design)
  - Solution A): reduce number of variables to 5 (equally for all subjects so that estimates of between-subject variability of network replicability is unaffected by this)
  - Solution B): use aggregate variables by construct as unweighted sum scores
  - Solution B): tune regularization parameter to err on the side of false positives
  - Solution B): estimate idiographic networks using multilevel estimation (mlVAR). Borrows information from group network to derive individual networks, thus more power, but comparisons become difficult to interpret as the "reference" group network cannot be constrained to be equal - perhaps there are solutions available though, eg. in psychonetrics package.
-->

# Results

### Network estimation

-   which estimation methods were tried

-   How did they perform, what needed to be adjusted

### Intra-individual network replicability (RQ1)

### Inter-individual variation in network replicability (RQ2)

# Discussion

### Limitations

-   ACCURACY OF ESTIMATES UNKNOWN: Uncertainty around parameter estimates is unknown. We cannot know whether dissimilarity of networks is due to unreliable estimates (too low power, measurement error) or because underlying data-generating process changes (non-stationarity, important variables missing from network)

-   subjective selection of included variables, individual estimates in this study should not be interpreted on substantive grounds, variables were mostly selected for their statistical properties in order to improve power

-   limitations of this data set for this research q, and constraints to generalizability (population, designs, time frame, estimation method)

-   We focus on similarity of global network structure, but there are many more ways to descibe and interpret networks which may or may not be relevant for replicability:
  - network comparison test
  - predictive networks models
  - sensitivity and specificity of recovered edges if true network (assumed to be) known
  
-   Imputation assumes MCAR but hard to check this assumption here
-   important assumption made by (idiographic) network models is that constructs were measured without error.


### Implications

-   relate to stationarity assumption
-   relate to idea of monitoring change, critical slowing down, phase transitions, ROM
-   implications for feasibility of this approach for research and applications
-   propose ideas for further research on this

### Conclusion

\newpage

# References

```{=tex}
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
```
::: {#refs custom-style="Bibliography"}
:::

\endgroup
